spring.application.name=rescatevial

# Configuracion temporal mientras desarrollamos la interfaz
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration